version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile1
    volumes:
      - .:/app
    environment:
      - TZ=Europe/Moscow
      # - event_id=1122397272
      - event_id=1794592932


